apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  secretName: letsencrypt-prod
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.chibuzonwobia.me
  dnsNames:
  - www.chibuzonwobia.me